module StrongSchema
  class Railtie < Rails::Railtie
  end
end


module StrongSchema
  module SchemaExtension
    def method_missing: (Symbol, *untyped) -> untyped
  end
end


module StrongSchema
  VERSION: String
end


module StrongSchema
  @setup_done: bool?

  def self.setup: () -> void

  def self.install_boot_hook: () -> void
end
